name: iugu
description: Client Flutter/Dart de acesso aos principais recursos da Api da IUGU
version: 0.0.1-dev.1
homepage: https://github.com/Flutterando/iugu

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ">=3.0.0 <4.0.0"
  uuid: ">=2.0.0 <3.0.0"  

dev_dependencies:
  mockito: ^4.1.1
  test:
