name: iugu
description: Client Flutter/Dart de acesso aos principais recursos da Api da IUGU
version: 2.0.0+3
homepage: https://github.com/Flutterando/iugu

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dio: ^4.0.0-beta4
  uuid: ^3.0.1 
  meta: ^1.3.0 

dev_dependencies:
  mocktail: ^0.1.1
  test: ^1.16.5
